name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0
      - name: Compile
        shell: bash
        run: |
          zig build --release=safe
          zig build gen_registry
          zip -r registry.json.zip registry.json
          sha256sum registry.json registry.json.zip > checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          fail_on_unmatched_files: true
          generate_release_notes: false
          files: |
            registry.json.zip
            checksums.txt
            zig-out/bin/test-ls
